# syntax=docker/dockerfile:1

FROM golang:1.16-alpine AS build
COPY . /src
WORKDIR /src
RUN go mod download
RUN go build -o grpc_client ./template/main.go

FROM alpine:latest AS client
COPY ./ ./
WORKDIR /template
COPY --from=build /src/grpc_client /usr/local/bin/grpc_client

EXPOSE 8080

CMD ["grpc_client"]