# syntax=docker/dockerfile:1

FROM golang:1.16-alpine AS builder
COPY . /src
WORKDIR /src
RUN go mod download
RUN go build -o grpc_server ./greeter_server/main.go

FROM alpine:latest AS server
COPY --from=builder /src/grpc_server /usr/local/bin/grpc_server

EXPOSE 50052

CMD ["grpc_server"]