# syntax=docker/dockerfile:1

FROM golang:1.16-alpine
WORKDIR /
RUN go version

COPY ./ ./
RUN go mod download
RUN go build -o /grpc_server ./greeter_server/main.go

EXPOSE 50052

CMD ["./grpc_server"]