# syntax=docker/dockerfile:1

## Build
FROM golang:1.16-buster AS build
WORKDIR /grpc_server
COPY . .
RUN go mod download
RUN go build -o /grpc_server greeter_server/main.go

FROM gcr.io/distroless/base-debian10
WORKDIR /
COPY --from=build /grpc_server /grpc_server
EXPOSE 8080
USER nonroot:nonroot

ENTRYPOINT ["/grpc_server"]